import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './login.css';
import './pages.css';

const ROOT = 'http://localhost:3000/api/v1';
const STORAGE_KEY = 'roadpulse.admin.session';
let refreshPromise = null;
const demoData = { generatedAt: new Date().toISOString(), trafficWindowMinutes: 30, metrics: { activeDrivers: 28, matchedPointCount: 4812, monitoredRoadCount: 86, pendingIncidentCount: 7 }, trafficRoads: [{ osmId: '75403343', roadName: 'Harper Road', sampleCount: 421, driverCount: 16, medianSpeedKph: 17 }, { osmId: '777308334', roadName: 'Okomfo Anokye Road', sampleCount: 382, driverCount: 13, medianSpeedKph: 23 }, { osmId: '191894078', roadName: 'Bantama Road', sampleCount: 266, driverCount: 10, medianSpeedKph: 34 }, { osmId: '81554804', roadName: 'Kejetia Road', sampleCount: 189, driverCount: 8, medianSpeedKph: 9 }], incidents: [{ id: 'inc-1', type: 'Road construction', roadName: 'Kejetia Road', city: 'Kumasi', severity: 'high', status: 'pending', confirmationCount: 4, reporterName: 'Kwame Boateng', createdAt: new Date(Date.now() - 8 * 60000).toISOString() }, { id: 'inc-2', type: 'Flooding', roadName: 'Harper Road', city: 'Kumasi', severity: 'medium', status: 'verified', confirmationCount: 12, reporterName: 'Adwoa Mensah', createdAt: new Date(Date.now() - 24 * 60000).toISOString() }, { id: 'inc-3', type: 'Vehicle breakdown', roadName: 'Spintex Road', city: 'Accra', severity: 'low', status: 'pending', confirmationCount: 2, reporterName: 'Kofi Asare', createdAt: new Date(Date.now() - 51 * 60000).toISOString() }] };
const number = new Intl.NumberFormat('en-GH');
const trafficLevel = (speed) => speed == null ? ['No speed', 'moderate'] : speed < 12 ? ['Severe', 'severe'] : speed < 25 ? ['Heavy', 'heavy'] : speed < 40 ? ['Moderate', 'moderate'] : ['Free', 'free'];
const relativeTime = (iso) => { const m = Math.max(0, Math.round((Date.now() - new Date(iso)) / 60000)); return m < 1 ? 'Just now' : m < 60 ? `${m} min ago` : `${Math.round(m / 60)} hr ago`; };
const loadSession = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); } catch { return null; } };
const saveSession = (session) => localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
const apiRoot = (url) => url.replace(/\/admin\/dashboard(?:\?.*)?$/, '');
async function refreshSession(root, session) { if (!refreshPromise) refreshPromise = fetch(`${root}/auth/admin/refresh`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ refreshToken: session.refreshToken, adminId: session.admin.id }) }).then(async (response) => { const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Session expired'); const next = { ...session, accessToken: body.data.access_token, refreshToken: body.data.refresh_token }; saveSession(next); return next; }).finally(() => { refreshPromise = null; }); return refreshPromise; }
async function authorisedRequest(url, session, onSession) { const request = (accessToken) => fetch(url, { headers: { Authorization: `Bearer ${accessToken}` } }); let response = await request(session.accessToken); if (response.status !== 401) return response; const next = await refreshSession(apiRoot(url), session); onSession(next); return request(next.accessToken); }

function Login({ onLogin }) { const [email, setEmail] = useState('admin@roadplus.com'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch(`${ROOT}/auth/admin/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Unable to sign in'); const session = { accessToken: body.data.access_token, refreshToken: body.data.refresh_token, admin: body.data.admin }; saveSession(session); onLogin(session); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to sign in'); } finally { setLoading(false); } } return <main className="login-page"><section className="login-hero"><a className="brand" href="#top"><span className="brand-mark">RP</span><span><strong>RoadPulse</strong><small>COMMAND</small></span></a><div><p className="eyebrow">GHANA MOBILITY OPERATIONS</p><h1>Turn movement data into better roads.</h1><p>Review live road conditions, driver coverage, and community incident signals in one secure workspace.</p></div><div className="login-signal"><span className="pulse"/><span>Secure administrator access</span></div></section><section className="login-card-wrap"><form className="login-card" onSubmit={submit}><p className="eyebrow">ADMINISTRATOR SIGN IN</p><h2>Welcome back</h2><p className="login-subtitle">Sign in to RoadPulse Command.</p><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required /></label>{error && <p className="login-error">{error}</p>}<button type="submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in to command'}</button><p className="login-footnote">Protected operations workspace · Session refresh is handled automatically.</p></form></section></main>; }

function Sidebar({ active, setActive }) { const links = [['overview', '◉', 'Network overview'], ['traffic', '⌁', 'Traffic intelligence'], ['reports', '△', 'Incident reports']]; return <aside className="sidebar"><a className="brand" href="#top"><span className="brand-mark">RP</span><span><strong>RoadPulse</strong><small>COMMAND</small></span></a><nav className="nav-links">{links.map(([id, icon, label]) => <button key={id} className={active === id ? 'active' : ''} onClick={() => setActive(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-note"><span className="pulse"/><div><strong>Live operations</strong><small>Updates from matched driver GPS points</small></div></div></aside>; }
function Metric({ icon, tone, label, value, detail }) { return <article><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{number.format(value)}</strong><small>{detail}</small></div></article>; }
function RoadRow({ road }) { const [label, tone] = trafficLevel(road.medianSpeedKph); return <div className="road-row"><div><div className="road-name">{road.roadName}</div><div className="road-meta">{road.driverCount} drivers · {road.sampleCount} matched points · OSM {road.osmId}</div></div><div className="road-speed">{road.medianSpeedKph == null ? '—' : `${Math.round(road.medianSpeedKph)} km/h`}<small>median</small></div><span className={`traffic-tag traffic-${tone}`}>{label}</span></div>; }
function RoadMap() { return <div className="road-map"><div className="map-grid"/><span className="map-label label-a">Kumasi</span><span className="map-label label-b">Accra</span><span className="road-line line-a"/><span className="road-line line-b"/><span className="road-line line-c"/><span className="road-line line-d"/><span className="map-dot dot-a"/><span className="map-dot dot-b"/></div>; }
function IncidentRow({ incident }) { return <tr><td><div className="incident-main">{incident.type}</div><div className="incident-sub">Reported by {incident.reporterName}</div></td><td>{incident.roadName}<div className="incident-sub">{incident.city}</div></td><td><span className={`badge severity-${incident.severity}`}>{incident.severity}</span></td><td>{incident.confirmationCount} confirmations</td><td>{relativeTime(incident.createdAt)}</td><td><span className={`badge status-${incident.status}`}>{incident.status}</span></td></tr>; }
function ReportsTable({ incidents }) { return <div className="table-wrap"><table><thead><tr><th>Incident</th><th>Location</th><th>Severity</th><th>Community confirmation</th><th>Reported</th><th>Status</th></tr></thead><tbody>{incidents.length ? incidents.map((incident) => <IncidentRow key={incident.id} incident={incident}/>) : <tr><td colSpan="6">No incident reports found.</td></tr>}</tbody></table></div>; }
function Overview({ data, setActive }) { return <><section className="metrics"><Metric icon="⌁" tone="blue" label="Active drivers" value={data.metrics.activeDrivers} detail="currently sending trips"/><Metric icon="◌" tone="teal" label="Matched points" value={data.metrics.matchedPointCount} detail={`in the last ${data.trafficWindowMinutes} min`}/><Metric icon="▤" tone="violet" label="Roads observed" value={data.metrics.monitoredRoadCount} detail="with traffic samples"/><Metric icon="△" tone="amber" label="Pending reports" value={data.metrics.pendingIncidentCount} detail="require attention"/></section><section className="grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SNAPSHOT</p><h2>Road conditions requiring attention</h2></div><button className="text-action" onClick={() => setActive('traffic')}>Open traffic →</button></div><div className="road-list">{data.trafficRoads.slice(0, 3).map((road) => <RoadRow key={road.osmId} road={road}/>)}</div></article><article className="panel"><div className="panel-heading"><div><p className="eyebrow">SNAPSHOT</p><h2>Newest community signals</h2></div><button className="text-action" onClick={() => setActive('reports')}>Open reports →</button></div><div className="snapshot-incidents">{data.incidents.slice(0, 3).map((incident) => <div key={incident.id}><strong>{incident.type}</strong><span>{incident.roadName}, {incident.city}</span><small>{relativeTime(incident.createdAt)} · {incident.confirmationCount} confirmations</small></div>)}</div></article></section></>; }
function Traffic({ data }) { return <section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">LIVE ROAD CONDITIONS</p><h2>Traffic intelligence</h2><p className="page-copy">Traffic levels are calculated from map-matched GPS points in the selected time window.</p></div><span className="legend"><i className="green"/> Free <i className="orange"/> Heavy <i className="red"/> Severe</span></div><RoadMap/><div className="road-list">{data.trafficRoads.length ? data.trafficRoads.map((road) => <RoadRow key={road.osmId} road={road}/>) : <p className="focus-copy">No matched road samples were received in this window.</p>}</div></section>; }
function Reports({ data }) { return <section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">COMMUNITY SIGNALS</p><h2>Incident reports</h2><p className="page-copy">Review every recent driver-submitted incident and its community confirmations.</p></div><span className="table-caption">Newest reports first</span></div><ReportsTable incidents={data.incidents}/></section>; }
function Dashboard({ session, onSession, onLogout }) { const [data, setData] = useState(demoData); const [windowMinutes, setWindowMinutes] = useState('30'); const [message, setMessage] = useState('Showing demo data. Load live operations data when ready.'); const [loading, setLoading] = useState(false); const [live, setLive] = useState(false); const [active, setActive] = useState('overview'); async function loadLiveData() { setLoading(true); try { const url = new URL(`${ROOT}/admin/dashboard`); url.searchParams.set('windowMinutes', windowMinutes); const response = await authorisedRequest(url.toString(), session, onSession); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'The dashboard request failed'); setData(body.data); setLive(true); setMessage(`Live data loaded at ${new Date(body.data.generatedAt).toLocaleTimeString()}.`); } catch (caught) { const error = caught instanceof Error ? caught.message : 'Unknown error'; setMessage(`Could not load live data: ${error}`); if (error === 'Session expired') onLogout(); } finally { setLoading(false); } } const titles = { overview: ['Network overview', 'A concise snapshot of current network activity.'], traffic: ['Traffic intelligence', 'Road-by-road conditions derived from matched driver movement.'], reports: ['Incident reports', 'Community reports requiring operational review.'] }; return <div className="app-shell"><Sidebar active={active} setActive={setActive}/><main id="top"><header className="topbar"><div><p className="eyebrow">GHANA MOBILITY OPERATIONS</p><h1>{titles[active][0]}</h1><p className="page-subtitle">{titles[active][1]}</p></div><div className="header-actions"><span className="live-status"><span className="pulse"/>{live ? 'Live data connected' : 'Demo view'}</span><button className="signout" onClick={onLogout}>Sign out</button></div></header><section className="connection-panel"><div className="connection-copy"><strong>{session.admin.email}</strong><span>Administrator session</span></div><label>Traffic window<select value={windowMinutes} onChange={(e) => setWindowMinutes(e.target.value)}><option value="15">Last 15 minutes</option><option value="30">Last 30 minutes</option><option value="60">Last hour</option><option value="1440">Last 24 hours</option></select></label><button type="button" onClick={loadLiveData} disabled={loading}>{loading ? 'Loading…' : 'Load live data'}</button></section><p className="connection-message">{message}</p>{active === 'overview' && <Overview data={data} setActive={setActive}/>} {active === 'traffic' && <Traffic data={data}/>} {active === 'reports' && <Reports data={data}/>}</main></div>; }
function Root() { const [session, setSession] = useState(loadSession); const logout = () => { localStorage.removeItem(STORAGE_KEY); setSession(null); }; return session ? <Dashboard session={session} onSession={setSession} onLogout={logout}/> : <Login onLogin={setSession}/>; }
createRoot(document.getElementById('root')).render(<Root/>);
