import { useEffect, useState } from 'react';

export default function TrafficSimulation({ request, onMessage }) {
  const [status, setStatus] = useState(null); const [scenario, setScenario] = useState('rush_hour'); const [busy, setBusy] = useState(false);
  const load = async () => { try { const response = await request('/admin/simulation'); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Unable to check simulation'); setStatus(body.data); } catch (error) { onMessage(`Could not check simulation: ${error instanceof Error ? error.message : 'Unknown error'}`); } };
  useEffect(() => { void load(); const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, []);
  const control = async (action) => { setBusy(true); try { const response = await request(`/admin/simulation/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: action === 'start' ? JSON.stringify({ scenario }) : undefined }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Simulation request failed'); setStatus(body.data); onMessage(action === 'start' ? 'KNUST simulation started: simulated GPS and an incident report are now being generated.' : 'Traffic simulation stopped.'); } catch (error) { onMessage(`Could not ${action} simulation: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } };
  return <section className="simulation-panel"><div><p className="eyebrow">PRESENTATION MODE</p><h2>Traffic simulation · KNUST</h2><p className="page-copy">Creates simulated driver GPS and a clearly labelled incident report through the real tracking pipeline.</p></div><div className="simulation-controls">{status?.running ? <><span className="simulation-live">● Running · {status.driverCount} virtual drivers</span><button onClick={() => void control('stop')} disabled={busy} className="simulation-stop">{busy ? 'Stopping…' : 'Stop simulation'}</button></> : <><select value={scenario} onChange={(event) => setScenario(event.target.value)} disabled={busy}><option value="normal">Normal flow</option><option value="rush_hour">Rush-hour congestion</option><option value="incident">Incident bottleneck</option></select><button onClick={() => void control('start')} disabled={busy}>{busy ? 'Starting…' : 'Start simulation'}</button></>}</div></section>;
}
