import { useEffect, useState } from 'react';

export default function TrafficSimulation({ request, onMessage }) {
  const [status, setStatus] = useState(null); const [scenario, setScenario] = useState('rush_hour'); const [busy, setBusy] = useState(false);
  const load = async () => { try { const response = await request('/admin/simulation'); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Unable to check simulation'); setStatus(body.data); } catch (error) { onMessage(`Could not check simulation: ${error instanceof Error ? error.message : 'Unknown error'}`); } };
  // Check once when the panel opens. Continue polling only while a simulation
  // is active; otherwise the server log can look like traffic is still running.
  useEffect(() => { void load(); if (!status?.running) return undefined; const timer = setInterval(() => void load(), 5000); return () => clearInterval(timer); }, [status?.running]);
  const control = async (action) => { setBusy(true); try { const response = await request(`/admin/simulation/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: action === 'start' ? JSON.stringify({ scenario }) : undefined }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Simulation request failed'); setStatus(body.data); onMessage(action === 'start' ? 'Network simulation started: 110 drivers across 11 verified Kumasi road corridors.' : 'Simulation stopped and its generated traffic and incident data were removed.'); } catch (error) { onMessage(`Could not ${action} simulation: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } };
  return <section className="simulation-panel"><div><p className="eyebrow">PRESENTATION MODE</p><h2>Traffic simulation · Kumasi network</h2><p className="page-copy">Creates ten virtual drivers on each of eleven verified roads, with real aggregated free, moderate, heavy, and severe conditions.</p></div><div className="simulation-controls">{status?.running ? <><span className="simulation-live">● Running · {status.driverCount} virtual drivers · 11 roads · 10 per road</span><button onClick={() => void control('stop')} disabled={busy} className="simulation-stop">{busy ? 'Stopping…' : 'Stop simulation'}</button></> : <><select value={scenario} onChange={(event) => setScenario(event.target.value)} disabled={busy}><option value="normal">Normal flow</option><option value="rush_hour">Rush-hour congestion</option><option value="incident">Incident bottleneck</option></select><button onClick={() => void control('start')} disabled={busy}>{busy ? 'Starting…' : 'Start simulation'}</button></>}</div></section>;
}
